### ISSUE TITLE
Are there any settings? Not clear how to use it...

### ISSUE THREAD

**Issue by viaahmed** [Yeboster/autocomplete-obsidian#3]
It wasn't clear from the Readme.md what the suggestion library/dictionary will suggest, whether it will suggest a particular language or terms from body of knowledge or a basic dictionary...?

**Comment by viaahmed** [comment]
Understood it is for Latex.

**Comment by Yeboster** [comment]
Hello @viaahmed,
As stated in the readme, this plugin is still WIP, so I've done only a tiny part of what I have in mind to do (that's why there aren't settings, ...).

Since I created this plugin mainly to suggest latex functions, that's the main feature for it, as of now. Later on, I will add different providers (most used words into the current file, custom file given by the user, ...) and the user will be able to enable them individually, based on needs.

Let me know what priorities I should give to the features, given also the TODOs in the README.

Unfortunately, right now I am in the middle of the exam session so the development is slowed down.

**Comment by viaahmed** [comment]
No problem, take your time, Thanks for the efforts 🙂😊

**Comment by phlind** [comment]
Would it be possible to add a general autcomplete function with all words in the current file like in Sublime Text?

**Comment by viaahmed** [comment]
Yeah, it is in the Roadmap, @yeboster told me.

**Comment by Yeboster** [comment]
Hello,

I've almost finished the exam session so the development will start soon 👍 

@phlind yes, I've already started to develop the settings tab locally, but I'm thinking of what is the best architecture to manage everything correctly.

**Comment by Yeboster** [comment]
Settings tab has added in last releases. Closing the issue.
