### ISSUE TITLE
Ctrl n/p clash

### ISSUE THREAD

**Issue by viaahmed** [Yeboster/autocomplete-obsidian#4]
instead of jumping to next suggestion, the command created new file.

**Comment by Yeboster** [comment]
Hello @viaahmed,
I've bound `Ctrl+n/Arrow Down` and `Ctrl+p/Arrow up` to change suggestion to support Windows and macOS platforms. `Ctrl+p/n` bindings are for macOS platform and`Arrow Down/Up` are for the Windows platform.

In the next release, I will properly differentiate the helper suggestions with Windows/macOS bindins based on the current platform, instead of leaving only `Ctrl+n/p`.

**Comment by Yeboster** [comment]
Right now I'm not sure how to check if the plugin is running on Windows or Mac.
I've added in the suggestion prompt also the arrows keys. 

I don't think this is an issue any more. Please open it again if you have suggestions.
