### ISSUE TITLE
The "any word split by space" completion is great, but how to navigate the suggestions by keyboard?

### ISSUE THREAD

**Issue by lethefrost** [Yeboster/autocomplete-obsidian#5]
It looks like it pop up a list view of suggestions (just literally like the `<ul><li>` tag elements?), and user might need to use mouse to click one of them, or use tab to get the first suggestion. Could the style of it be a little more consistent with the style of the LaTeX keywords completion? Like, the same popup menu styling, the same operation logic (`⌃P`/`⌃N` or just `Up`/`Down` to navigate; `Enter` to select)

Thank you so much for bringing this useful plugin :D!

**Comment by Yeboster** [comment]
Hello there!
First of all I'm happy you like this plugin :) I'm developing this in my free time (while working and studying, so it's not easy). But the development has started and in the next days there should be some improvements!

> Could the style of it be a little more consistent with the style of the LaTeX keywords completion?

Well, since this is an Obsidian plugin it should follow the obsidian theme rules, but feel free to use a custom community theme. I'm using Obsidian css classes so if you change the theme it will be applied to this plugin as well.

> Like, the same popup menu styling, the same operation logic (⌃P/⌃N or just Up/Down to navigate; Enter to select)

I'm not sure to understand this point; I've added multiple ways to change the completion to fulfil the majority of users (so arrows and mac os bindings). What do you have in mind ?
---

**Comment by lethefrost** [comment]
> Hello there!
> First of all I'm happy you like this plugin :) I'm developing this in my free time (while working and studying, so it's not easy). But the development has started and in the next days there should be some improvements!
> 
> > Could the style of it be a little more consistent with the style of the LaTeX keywords completion?
> 
> Well, since this is an Obsidian plugin it should follow the obsidian theme rules, but feel free to use a custom community theme. I'm using Obsidian css classes so if you change the theme it will be applied to this plugin as well.
> 
> > Like, the same popup menu styling, the same operation logic (⌃P/⌃N or just Up/Down to navigate; Enter to select)
> 
> I'm not sure to understand this point; I've added multiple ways to change the completion to fulfil the majority of users (so arrows and mac os bindings). What do you have in mind ?

Hi Yeboster, I'm sorry, I've just realised that I've accidentally confused your plugin and [this one](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin) before... I just thought they were both written by you, so I've made some less than appropriate suggestions based on this misunderstanding. 

I guess now I get the difference: 
<img width="506" alt="Snip 2021-03-11, 12-18-48" src="https://user-images.githubusercontent.com/47198693/111052868-03f95a00-842d-11eb-893f-d77b916ca51e.png">this one is written by you, 
![image](https://user-images.githubusercontent.com/47198693/111052920-871ab000-842d-11eb-81da-8ad0f4d72b49.png) and this one is written by the `various complements` 's author tadashi. 

I was just confused why the `various complements` menu doesn't really work well and I can't switch between the items to select one, and wondering why not just use the same style of popup menu as the `autocomplete` uses, but now I fully understand it's because the two are written by different authors lol

I really appreciate your work and it does help people! And I sincerely apologise to you for my careless mistakes and bother.

**Comment by Yeboster** [comment]
Hi @lethefrost, thanks for the clarification and no worries about the misunderstanding. 
I'm glad you showed me the existence of this plugin because I think it's useless to work on two different plugins with the same concept in mind (autocompletion).
I'll contact Various Complements's author to find a way to collaborate and bring the most advanced and powerful Autocomplete!
