### ISSUE TITLE
Only works for words I've typed while suggestion dropdown is open

### ISSUE THREAD

**Issue by janacm** [Yeboster/autocomplete-obsidian#7]
Is it normal that I only get suggestions for words I've typed, while the suggestion dropdown is open? I don't get any suggestions for words in the current file I'm in, which I've typed previously. Is there a way to force the cache to pickup words in the current file?

<img width="489" alt="image" src="https://user-images.githubusercontent.com/2055312/111792450-a769c500-889a-11eb-9534-1872e8db6960.png">

Here's a picture showing that I have the word "discovered" in my current file, but when I press ctrl-space on "disc", I don't get any results.

**Comment by Yeboster** [comment]
Hello,

Thanks for the bug report.

There is a typo in your photo on the first written word "Discovered" it's
written "Dscovered" so that's why the suggestion is not showing up.

Right now the flow providers adds only words written in the current
session. In the next future a Current file provider will be added and it
will scan the current file and then the provider will suggest the words
already written.

Keep an eye on the plugin updates :)

Have a nice day!



janac meena ***@***.***> schrieb am Fr., 19. März 2021, 15:06:

**Comment by janacm** [comment]
Thanks for the response, great plugin, will watch for updates!
